# Generated by Django 3.2 on 2021-05-07 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_winner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
