# Generated by Django 3.2 on 2021-05-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20210507_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(choices=[('w', 'White'), ('b', 'Black'), ('-', 'Pending')], default='-', max_length=1),
            preserve_default=False,
        ),
    ]
