# Generated by Django 3.2 on 2021-05-09 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20210508_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.PositiveSmallIntegerField(default=3600, validators=[django.core.validators.MaxValueValidator(7200)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(choices=[('w', 'White'), ('b', 'Black'), ('-', 'Pending'), ('d', 'Draw')], max_length=1),
        ),
    ]
