# Generated by Django 3.2 on 2021-05-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20210509_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
        migrations.AddField(
            model_name='game',
            name='result',
            field=models.CharField(choices=[('w', 'White won'), ('b', 'Black won'), ('-', 'Pending'), ('d', 'Draw')], default='-', max_length=1),
        ),
    ]
