# Generated by Django 3.2 on 2021-05-15 21:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_game_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_fen',
            field=models.CharField(default='start', max_length=80),
        ),
        migrations.AddField(
            model_name='game',
            name='time_left_for_black',
            field=models.PositiveIntegerField(default=600000, validators=[django.core.validators.MaxValueValidator(1800000)]),
        ),
        migrations.AddField(
            model_name='game',
            name='time_left_for_white',
            field=models.PositiveIntegerField(default=600000, validators=[django.core.validators.MaxValueValidator(1800000)]),
        ),
    ]
