# Generated by Django 3.2 on 2021-05-16 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20210516_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='time_left_for_black',
        ),
        migrations.RemoveField(
            model_name='game',
            name='time_left_for_white',
        ),
    ]
