# Generated by Django 3.2 on 2021-05-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_alter_game_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='pgn',
            field=models.TextField(blank=True, default=''),
        ),
    ]
