# Generated by Django 3.1.7 on 2021-03-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210315_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='games_played',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
