# Generated by Django 3.2 on 2021-05-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210316_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='/media/profile_pictures/default.png', null=True, upload_to='profile_pictures'),
        ),
    ]
